# Generated by Django 4.2.14 on 2024-07-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
